// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvtBuKhj8RORmvtvbl3PZOPj7ZdsGbRk',
    appId: '1:335587421581:android:77931fa38f6ef5ad63a1c4',
    messagingSenderId: '335587421581',
    projectId: 'lab06-amst-1e71a',
    databaseURL: 'https://lab06-amst-1e71a-default-rtdb.firebaseio.com',
    storageBucket: 'lab06-amst-1e71a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUgaQk9WwVOXLeMXNgA4U_-shRmsboNw',
    appId: '1:335587421581:ios:4cfc964b94add49063a1c4',
    messagingSenderId: '335587421581',
    projectId: 'lab06-amst-1e71a',
    databaseURL: 'https://lab06-amst-1e71a-default-rtdb.firebaseio.com',
    storageBucket: 'lab06-amst-1e71a.appspot.com',
    iosClientId: '335587421581-qvdfqsn4d8kmoo5uroate2a63kknh23k.apps.googleusercontent.com',
    iosBundleId: 'com.example.amst6G4',
  );
}
